#!/usr/bin/env node
/**
 * Generates components/INDEX.md from components.json + each component's guideline.
 * The index is never edited by hand; scripts/check.mjs fails if it is out of date.
 *
 *   node scripts/build-index.mjs
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { root, foundationsDir } from "./foundations.mjs";
import { FOLDED } from "../cascade.mjs";

const CATEGORY_TITLES = {
  actions: "Actions",
  "chips-and-badges": "Chips & badges",
  "inputs-and-controls": "Inputs & controls",
  "cards-and-content": "Cards & content",
  "navigation-and-chrome": "Navigation & chrome",
  "overlays-and-feedback": "Overlays & feedback",
  "layout-and-surfaces": "Layout & surfaces",
};

function summary(guidePath) {
  if (!existsSync(guidePath)) return "⚠ guide missing";
  const lines = readFileSync(guidePath, "utf8").split("\n");
  // first plain sentence after the header/meta lines
  const line = lines.slice(1).find((l) => l.trim() && !l.startsWith("#") && !l.startsWith("`") && !l.startsWith(">"));
  return (line ?? "").trim().replace(/\|/g, "\\|");
}

export function renderComponentIndex() {
  const reg = JSON.parse(readFileSync(join(root, "components.json"), "utf8"));
  const utilities = JSON.parse(readFileSync(join(foundationsDir(), "utilities.json"), "utf8")).utilities;
  const code = (id) => (FOLDED.has(id) ? `in [${FOLDED.get(id)}.html](${FOLDED.get(id)}.html)` : `[${id}.html](${id}.html)`);
  const out = [
    "# Components",
    "",
    "<!-- Generated by scripts/build-index.mjs from components.json. Do not edit by hand. -->",
    "",
    "Every UI element AuctionWire screens are built from. **Use only these.** Each component has two",
    "files side by side in this folder:",
    "",
    "- **`<id>.md` — the guideline.** Read it to decide: when to use it, its variants, states and grid rules.",
    "- **`<id>.html` — the code.** Build from it: copy its markup into a screen, open it in a browser, or",
    "  drop it into an artifact. The rules under its \"component\" marker are the styling every screen uses.",
    "",
    "Never build from a guideline's Example.",
    "",
    `Status: ${Object.entries(reg.statusKey).map(([k, v]) => `**${k}** = ${v}`).join(" · ")}.`,
    "",
  ];
  for (const [cat, ids] of Object.entries(reg.categories)) {
    out.push(`## ${CATEGORY_TITLES[cat] ?? cat}`, "", "| Component | Class | Status | Code | What it is |", "|---|---|---|---|---|");
    for (const id of ids) {
      const c = reg.components[id];
      out.push(`| [${c.name}](${id}.md) | \`.${c.class}\` | ${c.status} | ${code(id)} | ${summary(join(root, c.guide))} |`);
    }
    out.push("");
  }
  out.push(
    "## Utility classes",
    "",
    "Helpers, not components. They are defined in the Foundations repo (`02-design-system/src/base.css`,",
    "listed in `02-design-system/utilities.json`) and can be used on any screen.",
    "",
    "| Group | Classes |",
    "|---|---|"
  );
  for (const [g, list] of Object.entries(utilities)) out.push(`| ${g} | ${list.map((c) => `\`.${c}\``).join(" ")} |`);
  out.push("");
  return out.join("\n");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, "components/INDEX.md"), renderComponentIndex());
  console.log("wrote components/INDEX.md");
}
