#!/usr/bin/env node
/**
 * AuctionWire Component Library — integrity check.
 *
 *   node scripts/check.mjs          (needs the Foundations library; see scripts/foundations.mjs)
 *
 * Fails (exit 1) when this library has drifted:
 *   - folder hygiene: components/ holds only <id>.css, coded/ only generated <id>.html
 *   - the components.css manifest and components/ disagree, or a file is imported twice
 *   - a component CSS file is not a component registered in the Foundations components.json,
 *     or a registered component has no CSS file here
 *   - a coded/<id>.html mirror is missing or stale vs the CSS it is generated from
 *   - a raw hex or deny-listed colour (every value must be a Foundations token)
 *   - a var(--aw-*) this CSS uses that the Foundations tokens.css / assets.css does not define
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { basename, join } from "node:path";
import { componentCssFiles } from "./components-css.mjs";
import { foundationsDir, root } from "./foundations.mjs";
import { renderComponentMirrors, CODED_DIR } from "./build-mirrors.mjs";

const errors = [];
const notes = [];
const fail = (m) => errors.push(m);
const read = (p) => readFileSync(join(root, p), "utf8");
const stripComments = (s) => s.replace(/\/\*[\s\S]*?\*\//g, "");

let fnd;
try {
  fnd = foundationsDir();
} catch (e) {
  console.error(`✗ ${e.message}`);
  process.exit(1);
}
notes.push(`foundations: ${fnd}`);
const reg = JSON.parse(readFileSync(join(fnd, "components.json"), "utf8"));

// ── Folder hygiene ───────────────────────────────────────────────────────
for (const n of readdirSync(join(root, "components")))
  if (n !== ".DS_Store" && !n.endsWith(".css")) fail(`components/${n}: components/ holds only <id>.css files`);
for (const n of readdirSync(join(root, CODED_DIR)))
  if (n !== ".DS_Store" && !n.endsWith(".html")) fail(`${CODED_DIR}/${n}: ${CODED_DIR}/ holds only generated <id>.html files`);

// ── Manifest ↔ files ↔ registry ──────────────────────────────────────────
let listed = [];
try {
  listed = componentCssFiles();
  const ids = listed.map((f) => f.id);
  if (new Set(ids).size !== ids.length) fail("components.css imports a file more than once");
  for (const { id, path, file } of listed) {
    if (!existsSync(file)) fail(`components.css imports ${path}, which doesn't exist`);
    if (!id.startsWith("_") && !reg.components[id]) fail(`${path} is not a registered component (prefix helper files with "_")`);
  }
  for (const f of readdirSync(join(root, "components")).filter((f) => f.endsWith(".css")))
    if (!ids.includes(basename(f, ".css"))) fail(`components/${f} is not imported by components.css`);
  for (const id of Object.keys(reg.components))
    if (!ids.includes(id)) fail(`component "${id}" is registered in the Foundations components.json but has no components/${id}.css here`);
} catch (e) {
  fail(`component CSS: ${e.message}`);
}

// ── Coded mirrors are generated, never hand-edited ───────────────────────
try {
  const mirrors = renderComponentMirrors();
  for (const [path, html] of mirrors) {
    if (!existsSync(join(root, path))) fail(`${path} is missing: run node scripts/build-mirrors.mjs`);
    else if (read(path) !== html) fail(`${path} is out of date: run node scripts/build-mirrors.mjs`);
  }
  for (const f of readdirSync(join(root, CODED_DIR)).filter((f) => f.endsWith(".html")))
    if (!mirrors.has(`${CODED_DIR}/${f}`)) fail(`${CODED_DIR}/${f} is not generated by build-mirrors.mjs (add it to scripts/specimens.mjs)`);
} catch (e) {
  fail(`component mirrors: ${e.message}`);
}

// ── Colours: Foundations tokens only ─────────────────────────────────────
const DENY = ["#16a34a", "#2563eb", "#4773b9", "#89afed", "#09090b", "#22c55e", "#ef4444"];
for (const { path, file } of listed) {
  const text = stripComments(readFileSync(file, "utf8")).toLowerCase();
  for (const hex of DENY) if (text.includes(hex)) fail(`${path}: uses deny-listed colour ${hex}`);
  for (const [, hex] of text.matchAll(/(?<![\w-])(#[0-9a-f]{3,8})\b/g)) fail(`${path}: raw colour ${hex} (use a Foundations token)`);
}

// ── Every var(--aw-*) resolves in the Foundations tokens ─────────────────
// Known open gap, recorded in AW_DesignLanguage decisions/2026-09-22-component-library-removal.md §7:
// the sample card photos point at image tokens nothing defines, so those photos render blank.
const KNOWN_UNDEFINED = new Set(["--aw-img-aaron", "--aw-img-cobb", "--aw-img-mantels", "--aw-img-slab", "--aw-img-hero"]);
const defined = new Set(
  ["src/tokens.css", "src/assets.css"] // assets.css defines the embedded-image tokens
    .flatMap((f) => [...readFileSync(join(fnd, f), "utf8").matchAll(/(--aw-[\w-]+)\s*:/g)].map(([, k]) => k))
);
const stillMissing = new Set();
for (const { path, file } of listed) {
  const text = stripComments(readFileSync(file, "utf8"));
  const local = new Set([...text.matchAll(/(--aw-[\w-]+)\s*:/g)].map(([, k]) => k));
  for (const [, v] of text.matchAll(/var\(\s*(--aw-[\w-]+)/g)) {
    if (defined.has(v) || local.has(v)) continue;
    if (KNOWN_UNDEFINED.has(v)) stillMissing.add(v);
    else fail(`${path}: uses ${v}, which the Foundations src/tokens.css or src/assets.css does not define`);
  }
}
if (stillMissing.size)
  notes.push(
    `known gap — ${stillMissing.size} image token(s) undefined, so those sample photos render blank: ` +
      `${[...stillMissing].join(", ")} (AW_DesignLanguage decisions/2026-09-22-component-library-removal.md §7)`
  );

if (notes.length) console.log(notes.map((n) => `• ${n}`).join("\n"));
if (errors.length) {
  console.error(`✗ ${errors.length} problem(s):\n` + errors.map((e) => `  - ${e}`).join("\n"));
  process.exit(1);
}
console.log(`✓ component library consistent (${listed.length} component CSS files, ${readdirSync(join(root, CODED_DIR)).filter((f) => f.endsWith(".html")).length} coded mirrors)`);
